/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'adixit' at '12/15/20 9:13 AM' with Gradle 3.0
 *
 * @author adixit, @date 12/15/20 9:13 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
